BethanysPieShopAdmin/Controllers/CategoryController.cs
using BethanysPieShopAdmin.Models;
using BethanysPieShopAdmin.Models.Repositories;
using BethanysPieShopAdmin.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace BethanysPieShopAdmin.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                CategoryListViewModel model = new CategoryListViewModel
                {
                    Categories = (await _categoryRepository.GetAllCategoriesAsync()).ToList()
                };
                return View(model);
            }
            catch(Exception ex)
            {
                ViewData["Error Message"] = $"Error occured: {ex.Message}";
            }


            return View(new CategoryListViewModel());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var category = await _categoryRepository.GetCategoryByIdAsync(id.Value);
            return View(category);
        }

        public async Task<IActionResult> Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind ("Name,Description,DateAdded")] Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await _categoryRepository.AddCategoryAsync(category);
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Adding the category failed please try again! Error: {ex.Message}");
                    return View(category);
                }
            }
            return View(category);
        }

        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var selectedCategory = await _categoryRepository.GetCategoryByIdAsync(id.Value);
            return View(selectedCategory);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _categoryRepository.UpdateCategoryAsync(category);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Updating the category failed, please try again! Error: {ex.Message}");
            }

            return View(category);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var selectedCategory = await _categoryRepository.GetCategoryByIdAsync(id);

            return View(selectedCategory);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int? CategoryId)
        {
            if (CategoryId == null)
            {
                ViewData["ErrorMessage"] = "Deleting the category failed, invalid ID!";
                return View();
            }

            try
            {
                await _categoryRepository.DeleteCategoryAsync(CategoryId.Value);
                TempData["CategoryDeleted"] = "Category deleted successfully!";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Deleting the category failed, please try again! Error: {ex.Message}";
            }

            var selectedCategory = await _categoryRepository.GetCategoryByIdAsync(CategoryId.Value);
            return View(selectedCategory);

        }

        public async Task<IActionResult> BulkEdit()
        {
            List<CategoryBulkEditViewModel> categoryBulkEditViewModels = new List<CategoryBulkEditViewModel>();

            var allCategories = await _categoryRepository.GetAllCategoriesAsync();
            foreach(var category in allCategories)
            {
                categoryBulkEditViewModels.Add(new CategoryBulkEditViewModel
                {
                    CategoryId = category.CategoryId,
                    Name = category.Name
                });
            }
            return View(categoryBulkEditViewModels);
        }

        [HttpPost]
        public async Task<IActionResult> BulkEdit(List<CategoryBulkEditViewModel> categoryBuldEditViewModels)
        {
            
            List<Category> categories = new List<Category>();

            foreach(var categoryVm in categoryBuldEditViewModels)
            {
                categories.Add(new Category
                {
                    CategoryId = categoryVm.CategoryId,
                    Name = categoryVm.Name
                });
            }

            await _categoryRepository.UpdateCategoryNamesAsync(categories);

            return RedirectToAction(nameof(Index));

        }

    }
}

BethanysPieShopAdmin/Controllers/OrderController.cs
using BethanysPieShopAdmin.Models;
using BethanysPieShopAdmin.Models.Repositories;
using BethanysPieShopAdmin.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShopAdmin.Controllers
{
    public class OrderController : Controller
    {

        private readonly IOrderRepository _orderRepository;

        public OrderController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;
        }

     
        public async Task<IActionResult> Index(int? orderId, int? orderDetailId)
        {
            OrderIndexViewModel orderIndexViewModel = new()
            {
                Orders = await _orderRepository.GetAllOrdersWithDetailsAsync()
            };

            if (orderId != null)
            {
                Order selectedOrder = orderIndexViewModel.Orders.Where(o => o.OrderId == orderId).Single();
                orderIndexViewModel.OrderDetails = selectedOrder.OrderDetails;
                orderIndexViewModel.SelectedOrderId = orderId;
            }

            if (orderDetailId != null)
            {
                var selectedOrderDetail = orderIndexViewModel.OrderDetails.Where(od => od.OrderDetailId == orderDetailId).Single();
                orderIndexViewModel.Pies = new List<Pie>() { selectedOrderDetail.Pie };
                orderIndexViewModel.SelectedOrderDetailId = orderDetailId;
            }
            return View(orderIndexViewModel);

        }


        public async Task<IActionResult> Details(int? orderId)
        {
            var result = await _orderRepository.GetOrderDetailsAsync(orderId);

            return View(result);
        }
    }
}

BethanysPieShopAdmin/Controllers/PieController.cs
using BethanysPieShopAdmin.Models;
using BethanysPieShopAdmin.Models.Repositories;
using BethanysPieShopAdmin.Models.ViewModels;
using BethanysPieShopAdmin.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;

namespace BethanysPieShopAdmin.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        public async Task<IActionResult> Index()
        {
            var pies = await _pieRepository.GetAllPiesAsync();
            return View(pies);
        }

        public async Task<IActionResult> Details(int id)
        {
            var pie = await _pieRepository.GetPieByIdAsync(id);
            return View(pie);
        }

        public async Task<IActionResult> Add()
        {
            var allCategories = await _categoryRepository.GetAllCategoriesAsync();

            IEnumerable<SelectListItem> selectListItems = new SelectList(allCategories,
                "CategoryId", "Name", null);
            PieAddViewModel pieViewModel = new() { Categories = selectListItems };

            return View(pieViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(PieAddViewModel pieAddViewModel)
        {
            if (ModelState.IsValid && pieAddViewModel != null)
            {
                var pie = pieAddViewModel.Pie;
                await _pieRepository.AddPieAsync(pie);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var allCategories = await _categoryRepository.GetAllCategoriesAsync();
                IEnumerable<SelectListItem> selectListItems = new SelectList(allCategories,
                    "CategoryId", "Name", null);

                pieAddViewModel.Categories = selectListItems;

                return View(pieAddViewModel);
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allCategories = await _categoryRepository.GetAllCategoriesAsync();

            IEnumerable<SelectListItem> selectListItems = new SelectList(allCategories, "CategoryId", "Name", null);

            var selectedPie = await _pieRepository.GetPieByIdAsync(id.Value);

            PieEditViewModel pieEditViewModel = new() { Categories = selectListItems, Pie = selectedPie };
            return View(pieEditViewModel);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(PieEditViewModel pieEditViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _pieRepository.UpdatePieAsync(pieEditViewModel.Pie);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return BadRequest();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Updating the category failed, please try again! Error: {ex.Message}");
            }

            var allCategories = await _categoryRepository.GetAllCategoriesAsync();

            IEnumerable<SelectListItem> selectListItems = new SelectList(allCategories, "CategoryId", "Name", null);

            pieEditViewModel.Categories = selectListItems;

            return View(pieEditViewModel);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var selectedCategory = await _pieRepository.GetPieByIdAsync(id);

            return View(selectedCategory);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int? pieId)
        {
            if (pieId == null)
            {
                ViewData["ErrorMessage"] = "Deleting the pie failed, invalid ID!";
                return View();
            }

            try
            {
                await _pieRepository.DeletePieAsync(pieId.Value);
                TempData["PieDeleted"] = "Pie deleted successfully!";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = $"Deleting the pie failed, please try again! Error: {ex.Message}";
            }

            var selectedPie = await _pieRepository.GetPieByIdAsync(pieId.Value);
            return View(selectedPie);
        }

        private int pageSize = 5;

        public async Task<IActionResult> IndexPaging(int? pageNumber)
        {
            var pies = await _pieRepository.GetPiesPagedAsync(pageNumber, pageSize);
            pageNumber ??= 1;

            var count = await _pieRepository.GetAllPiesCountAsync();

            return View(new PaginatedList<Pie>(pies.ToList(),count,pageNumber.Value,pageSize));
        }

        public async Task<IActionResult> IndexPagingSorting(string sortBy, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortBy;

            ViewData["IdSortParam"] = string.IsNullOrEmpty(sortBy) || sortBy == "id_desc" ? "id" : "id_desc";
            ViewData["NameSortParam"] = string.IsNullOrEmpty(sortBy) || sortBy == "name_desc" ? "name" : "name_desc";
            ViewData["PriceSortParam"] = string.IsNullOrEmpty(sortBy) || sortBy == "price_desc" ? "price" : "price_desc";

            var pies = await _pieRepository.GetPiesSortedAndPagedAsync(sortBy, pageNumber, pageSize);
            pageNumber ??= 1;

            var count = await _pieRepository.GetAllPiesCountAsync();

            return View(new PaginatedList<Pie>(pies.ToList(),count,pageNumber.Value,pageSize));
        }

        public async Task<IActionResult> Search(PieSearchViewModel? modelInput)
        {
            var allCategories = await _categoryRepository.GetAllCategoriesAsync();
            var model = new PieSearchViewModel();
            IEnumerable<SelectListItem> selectListItems = new SelectList(allCategories,
                "CategoryId", "Name", modelInput.SearchCategory);

            if(!string.IsNullOrEmpty(modelInput.SearchQuery))
            {
                var pies = await _pieRepository.SearchPies(modelInput.SearchQuery, modelInput.SearchCategory);

                model = new PieSearchViewModel()
                {
                    Categories = selectListItems,
                    Pies = pies,
                    SearchQuery = modelInput.SearchQuery,
                    SearchCategory = modelInput.SearchCategory
                };
            }
            else
            {
                model = new PieSearchViewModel()
                {
                    Categories = selectListItems,
                    Pies = new List<Pie>(),
                    SearchQuery = string.Empty,
                    SearchCategory = null
                };
            }

            return View(model);
        }

    }
}

BethanysPieShopAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bethany's Pie Shop</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/lib/toastr.js/toastr.js.map"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <base href="/" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                 aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                             alt="Bethany's Pie Shop Logo">
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle"
                                   data-toggle="dropdown"
                                   href="#"
                                   role="button"
                                   data-bs-toggle="dropdown"
                                   id="nav-dropdown"
                                   aria-expanded="false">
                                    Pies
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
                                    <li>
                                        <a asp-controller="Pie" asp-action="Index" class="dropdown-item">
                                            View all
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Pie" asp-action="IndexPaging" class="dropdown-item">
                                            View all paged
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Pie" asp-action="IndexPagingSorting" class="dropdown-item">
                                            View all paged and sorted
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Pie" asp-action="Search" class="dropdown-item">
                                            Search pies
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Pie" asp-action="Add" class="dropdown-item">
                                            Add new pie
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Pie" asp-action="Search" class="dropdown-item">
                                            Search Pie
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle"
                                   data-toggle="dropdown"
                                   href="#"
                                   role="button"
                                   data-bs-toggle="dropdown"
                                   id="nav-dropdown"
                                   aria-expanded="false">
                                    Categories
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="nav-dropdown">
                                    <li>
                                        <a asp-controller="Category" asp-action="Index" class="dropdown-item">
                                            View all
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Category" asp-action="BulkEdit" class="dropdown-item">
                                            Bulk edit
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Category" asp-action="Add" class="dropdown-item">
                                            Add Category
                                        </a>
                                    </li>
                                    <li>
                                        <a asp-controller="Category" asp-action="BulkEdit" class="dropdown-item">
                                            Bulk Edit
                                        </a>
                                    </li>
                                </ul>
                            </li>


                            <li class="nav-item">
                                <a asp-controller="Order" asp-action="Index" class="nav-link">
                                    Orders
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
        </header>

        @RenderBody()
        @RenderSection("Scripts", required: false)
        <script>

            $.validator.methods.range = function (value, element, param) {
                var globalizedValue = value.replace(",", ".");
                return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]);
            }

            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value);
            }
        </script>
    </div>
</body>
</html>